
export enum Type {
    ERC721 = "ERC721",
    ERC1155 = "ERC1155",
    ERC20 = "ERC20",
}

export enum Network {
    ETHEREUM_MAINNET = "ETHEREUM_MAINNET",
    ETHEREUM_ROPSTEN = "ETHEREUM_ROPSTEN",
    ETHEREUM_GOERLI = "ETHEREUM_GOERLI",
    AVALANCHE_MAINNET = "AVALANCHE_MAINNET",
    AVALANCHE_FUJI = "AVALANCHE_FUJI",
    POLYGON_MAINNET = "POLYGON_MAINNET",
    POLYGON_MUMBAI = "POLYGON_MUMBAI",
    BINANCE_MAINNET = "BINANCE_MAINNET",
    BINANCE_TESTNET = "BINANCE_TESTNET",
}
